# Generated by Django 5.0.6 on 2024-07-12 11:54

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, storage=chat.models.MediaStorage(), upload_to='chat_files/'),
        ),
    ]
